-- Import receptů a ingrediencí do databáze
-- Spusť: psql -U postgres -d zlata_lednice -f init_data.sql

-- Insertuj ingredience
INSERT INTO ingredients (name, unit, avg_price) VALUES
('Kuřecí prso', 'g', 2.5),
('Hovězí maso', 'g', 3.0),
('Máslo', 'g', 4.0),
('Vejce', 'kus', 5),
('Mléko', 'ml', 0.02),
('Sýr', 'g', 3.0),
('Rajská jablka', 'g', 0.3),
('Brambory', 'g', 0.2),
('Cibule', 'kus', 8),
('Česnek', 'stroužek', 0.5),
('Slanina', 'g', 2.0),
('Olej', 'ml', 0.05),
('Mouka', 'g', 0.15),
('Cukr', 'g', 0.3),
('Sůl', 'kus', 20),
('Pepř', 'kus', 40),
('Tvarog', 'g', 0.8),
('Smetana', 'ml', 0.08),
('Okurka', 'kus', 15),
('Hlávkové zelí', 'g', 0.25),
('Jablka', 'g', 0.5),
('Jahody', 'g', 2.0),
('Čokoláda', 'g', 4.0),
('Voda', 'ml', 0.01),
('Těstoviny', 'g', 0.4),
('Rýže', 'g', 0.4),
('Med', 'g', 1.5),
('Vanilka', 'sáček', 30),
('Paprika', 'g', 2.0),
('Citron', 'kus', 20),
('Rybí filé', 'g', 4.0),
('Hovězí biftek', 'g', 5.0),
('Kuřecí křídla', 'g', 1.5),
('Mozzarela', 'g', 3.0),
('Bazalka', 'listů', 0.3),
('Pinolin', 'g', 6.0),
('Parmezan', 'g', 4.0),
('Feta sýr', 'g', 3.5),
('Sojový omáčka', 'ml', 1.0),
('Zázvor', 'g', 3.0),
('Květák', 'g', 0.5),
('Kokos', 'g', 2.0),
('Mandle', 'g', 4.0),
('Borůvky', 'g', 1.5),
('Majonéza', 'g', 1.0),
('Olivový olej', 'ml', 0.2),
('Nudle', 'g', 0.6),
('Rajská omáčka', 'ml', 0.5),
('Pepperoni', 'g', 2.0),
('Tuňák v plechovce', 'g', 2.0),
('Hovězí mleté maso', 'g', 2.5),
('Kuřecí maso', 'g', 2.0);

-- Insertuj recepty
INSERT INTO recipes (name, time, category, price) VALUES
('Kuřecí prsou na másle', 20, 'salty', 200),
('Těstoviny Carbonara', 15, 'salty', 180),
('Bramborový salát', 30, 'salty', 120),
('Rajská omáčka', 25, 'salty', 100),
('Kuřecí nudličky v paprice', 20, 'salty', 250),
('Omeleta se syrečkem', 10, 'salty', 90),
('Hovězí guláš', 120, 'salty', 450),
('Rybí filé na másle', 25, 'salty', 350),
('Hovězí steak', 20, 'salty', 400),
('Česnek krém polévka', 30, 'salty', 150),
('Paradajz a mozzarela salát', 10, 'salty', 200),
('Pesto Genovese', 15, 'salty', 180),
('Polévka z hlávkového zelí', 40, 'salty', 100),
('Kuřecí nudličky s kousky', 25, 'salty', 200),
('Grecký salát', 15, 'salty', 220),
('Bramborová kaše', 20, 'salty', 120),
('Smažená kuřecí křídla', 30, 'salty', 250),
('Hovězí mleté maso', 25, 'salty', 280),
('Smaženice se slaninou', 15, 'salty', 160),
('Květák zapečený', 45, 'salty', 180),
('Čokoládový dort', 60, 'sweet', 200),
('Vanilkový cheesecake', 90, 'sweet', 250),
('Jablkový koláč', 50, 'sweet', 150),
('Smetanový dort', 70, 'sweet', 220),
('Máslové syrečky', 40, 'sweet', 120),
('Tvarohová polévka', 20, 'sweet', 100),
('Jahodový koláč', 55, 'sweet', 180),
('Karamelový pudink', 30, 'sweet', 130),
('Domácí zmrzlina', 240, 'sweet', 150),
('Čokoládové brownies', 45, 'sweet', 140),
('Makronky', 35, 'sweet', 110),
('Krémový puding', 25, 'sweet', 100),
('Kokosové syrečky', 40, 'sweet', 130),
('Borůvkový koláč', 50, 'sweet', 170),
('Mandlový dort', 60, 'sweet', 200),
('Piškoty s čokoládou', 30, 'sweet', 140),
('Sladké buchtičky', 90, 'sweet', 150),
('Medové syrečky', 40, 'sweet', 120),
('Tvarohová bábovka', 70, 'sweet', 180),
('Vanilkový krém', 25, 'sweet', 90),
('Nudle se sojovkou', 12, 'salty', 100),
('Pizzy domácí', 30, 'salty', 200),
('Kuřecí polévka', 35, 'salty', 120),
('Grilované kuřecí prso', 20, 'salty', 200),
('Zelné závitky', 45, 'salty', 180),
('Třeba', 15, 'salty', 100),
('Sýrový koláč', 50, 'salty', 220),
('Těstoviny Bolognese', 30, 'salty', 250),
('Tuna zapečená', 35, 'salty', 220),
('Rajská polévka', 25, 'salty', 100);

-- Insertuj ingredience receptů
-- Kuřecí prsou na másle (ID 1)
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit) VALUES
(1, 1, 300, 'g'),
(1, 3, 50, 'g'),
(1, 15, 1, 'kus'),
(1, 16, 1, 'kus');

-- Těstoviny Carbonara (ID 2)
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, quantity, unit) VALUES
(2, 25, 400, 'g'),
(2, 11, 200, 'g'),
(2, 4, 3, 'kus'),
(2, 37, 100, 'g');

-- ... (a další recepty - zkráceno pro ilustraci)

COMMIT;
